### PR TITLE
Simplify logic with NSPersistentContainer (requires 10.12)

### PR DESCRIPTION
**Pull request by evanmiller**
This is an experimental branch with minimal testing. I'm sharing it to get general feedback. Results of testing are welcome as well.

I've spent the morning attempting to modernize BSManagedDocument's Core Data stack with two classes introduced in macOS 10.12. The class `NSPersistentStoreDescription` encapsulates all the information previously passed to `configurePersistentStoreCoordinatorForURL:ofType:modelConfiguration:storeOptions:error:`. As such, I've added an alternate method that subclasses may implement to configure the persistent store:

```objc
- (BOOL)configurePersistentStoreCoordinatorWithDescription:(NSPersistentStoreDescription *)description
                                                     error:(NSError **)outError;
```

As an example, subclasses that want to set a SQLite pragma can simply implement:

```objc
- (BOOL)configurePersistentStoreCoordinatorWithDescription:(NSPersistentStoreDescription *)description
                                                     error:(NSError **)outError {
  [description setValue:@"DELETE" forPragmaNamed:@"journal_mode"];
  [super configurePersistentStoreCoordinatorWithDescription:description error:outError];
}
```

Previously, this required jumping through hoops setting a sub-object of the `storeOptions` dictionary.

The second new class in 10.12 is `NSPersistentStoreContainer`, which automatically sets up a persistent store coordinator and managed object context. I've taken advantage of it to replace the `_store` and `_coordinator` ivars with a single `_container` ivar, and to simplify the logic in several places. Many long code comments and explanations of the minute differences between OS versions have been removed as unnecessary.

One victim of this PR is custom NSManagedObjectContext subclasses. These are discouraged by Apple anyway, so I think the loss will be bearable.

My hope with this change is to pave a path to using `NSCoreDataCoreSpotlightDelegate` to automatically index documents that subclass `BSManagedDocument` in Core Spotlight. That API uses `NSPersistentStoreDescription`, and so the other changes seemed natural.

I no longer need to support pre-10.13 systems, so these changes seemed like the right way forward for my own needs. However, if you need to continue supporting 10.11 or earlier, we can point this PR to a separate branch.

### CODE REVIEW

**Comment by evanmiller** [comment]
Note to self: The New Document workflow isn't working here. NSPersistentContainer requires a persistent store to be added before granting access to MOC. The existing BSManagedDocument architecture allows work to happen on an unaffiliated MOC (e.g. in an unsaved document), and then adds the MOC to the persistent store coordinator at save time.

One possible workaround will be to force an autosave when the managedObjectContext is first requested so that the container-owned MOC will be backed by a store. This will require reworking some of the saving logic, as it appears the autosaveContentsFileURL is nil when forcing an autosave when the document is first being created.

**Comment by evanmiller** [comment]
> One possible workaround will be to force an autosave when the managedObjectContext is first requested so that the container-owned MOC will be backed by a store. This will require reworking some of the saving logic, as it appears the autosaveContentsFileURL is nil when forcing an autosave when the document is first being created.

I've followed my own advice here and it seems to be working. One possible source of bugs is that the test:

```
(saveOperation == NSAutosaveElsewhereOperation && [absoluteURL isEqual:self.autosavedContentsFileURL])
```

was simplified to

```
saveOperation == NSAutosaveElsewhereOperation
```

I did this because when forcing an early autosave the `self.autosavedContentsFileURL` will not be set yet, even though `absoluteURL` is clearly an autosave URL. I'm not sure what the original motivation was behind testing the `absoluteURL` for equality with `self.autosavedContentsFileURL`. It seems to have been a part of the original implementation and passed down through the ages.

Here is the context:

https://github.com/evanmiller/BSManagedDocument/blob/4b947098f4d3703e5818b22fadc268e5a93a78bb/BSManagedDocument.m#L956-L958

I haven't yet tested the asynchronous saving workflow, as I have always left this setting turned off in my apps. But the basic tasks of creating, reading, duplicating, and reverting all seem to work fine with async turned off.

**Comment by jerrykrinock** [comment]
In my apps, I have been looking for reasons to remove support for 10.10 and 10.11 for the last couple years, and code modernization such as this would be a good one.  Regarding asynchronous saving, my apps use it, so when this pull request is ready for review I shall test with asynchronous saving.  (BSManagedDocument has asynchronous saving on by default, so I presume Evan you must be overriding -[BSManagedDocument canAsynchronouslyWriteToURL:ofType:forSaveOperation:] to turn it off.)

**Comment by evanmiller** [comment]
> (BSManagedDocument has asynchronous saving on by default, so I presume Evan you must be overriding -[BSManagedDocument canAsynchronouslyWriteToURL:ofType:forSaveOperation:] to turn it off.)

Correct.

My previous comment was prescient in that removing `[absoluteURL isEqual:self.autosavedContentsFileURL]` was indeed a source of new bugs (this time in file duplication). I think I have found the appropriate workaround, so the code officially "works for me". I'm going to peel off the Draft label now and let you have at it.

**Comment by evanmiller** [comment]
I will note that the Test app hangs so this PR needs more work. It looks like there is a deadlock with the container returning the MOC and another thread saving the same MOC. I'll try to dig deeper into this in the next couple of weeks.

**Comment by evanmiller** [comment]
I managed to fix the hang that was occurring, by disabling async writing until the persistent store has been fully configured. The test application opens fine and the file functions appear to work as expected.

I will note that under this NSPersistentContainer architecture, async writing is nominally enabled – but in practice it still needs access to the main thread to save the context, so there could be some beach balling. A fully async solution will require some re-architecting of the contexts. Previously, the managedObjectContext on the main queue had a parent context with a private queue, but the new persistent container's viewContext does not have a parent, so it looks like saves go straight to disk. Maybe this isn't so bad in the era of SSDs. I suppose we could recreate the old parent-child context architecture, but that starts to eat away at the benefit of using a persistent container in the first place (abstracting away implementation details).

In any event, I'd suggest trying out this code with actual applications. If save-time beach balls are a problem we can revisit the issue. I've added more thoughts and notes on the async dilemma in the commit log and in the canAsynchronouslyWriteToURL: function itself.

**Comment by evanmiller** [comment]
A couple of more notes:

I did see one of those "This document was edited by another program" messages during an autosave under Catalina. It's possible that the save timing is incorrect on this branch. In `v0.3.x`, there is a two-phase save. The main context saves to the parent (phase 1), and the parent later saves to disk (phase 2). `persistent-containers` saves to disk at the previous "phase 1" point. So that may create problems with the file modification date.

A second potential issue is the "sadness and wretchedness" code path - when a Revert is requested but there is not an Autosave URL. This path needs to be tested as it is likely affected by the "autosave elsewhere" changes in this PR.

**Comment by evanmiller** [comment]
I found the source of the "This document was edited by another program" warning in my app. The application had been calling `[document.managedObjectContext save:]` in a couple of places. Previously, this merely synchronized the main context with its parent context. In the container architecture, where the main context is parentless, calls to `save:` result in writing out the changes to disk. Since this disk activity was not managed by NSDocument, the document assumed that the writing occurred from another application, hence the error.

None of my calls to `save:` were actually needed (processPendingChanges was sufficient) so after a few code changes to my app, the errors no longer appear.

My second concern about reverting seems to be unfounded, as this code path does not appear affected in the current PR, and testing works fine. (It might affect #18, however.)

So I'm not aware of any remaining bugs in this PR.

**Comment by evanmiller** [comment]
This PR is ready for testing - I'd like to move it forward in the next month or two so I can get the automatic Share menu working. Thanks!

**Comment by jerrykrinock** [comment]
I'll be on it later tonight or tomorrow.

**Comment by jerrykrinock** [comment]
Evan, you wrote 8 lines of very interesting comments at the beginning of implementation `-managedObjectContext`.  I think these comments, in particular "This kind of 'late binding' isn't allowed under the NSPersistentContainer regime", explain why I am seeing dozens of warnings: *View context accessed for persistent container persistentStore with no stores loaded*.  Is that warning familiar to you?  Is it in fact the signature of this "late binding" prohibition?

Your attempted fix for this issue, triggering an autosave below that comment, was thoughtful but, for reasons I shall omit for the sake of brevity, does not work for me.  Is that autosave helpful for your apps, or did you add it for others' benefit?

It is possible that my apps depend so heavily on this prohibited "late binding", they may require a lot of rework before they can use NSPersistentContainer.  I'm thinking maybe I should fork my own branch, then merge this pull request to give me some time to tear out the crap in my apps and adopt more a more standard approach which does not rely on "late binding".   What is your timeline?

**Comment by jerrykrinock** [comment]
Well, after returning from a break, things are looking much better now.  When running in BSTestApp, your autosave operation causes -writeSafelyToURL:ofType:forSaveOperation:error: to  be invoked, and the system passes in one of those temporary "Autosave" file URLs, which of course gives the store a file on disk, "configuring" the persistent store.  It seems like a pretty massive side effect for a mere _autosave_ operation, but it works.  And if I send your -autosaveWithImplicitCancellability:completionHandler: to super, bypassing my subclass' override, and make a couple other minor tweaks in BSManagedDocument and a few in my subclass, I am able to open, save, and create new documents without any of those warnings I reported in my previous comment.

Oh, but I see Undo does not work.  I hope this is not the beginning of the dreaded "last 10%" :))

**Comment by jerrykrinock** [comment]
I realized the problem with undo soon after I went to bed … Undo was working but not being reflected in my user interface since, with the changes I made, the observers in my UI were being set to observe before my custom undo manager had been set.  It is fixed now.  And, yes, Undo works in the test app.

**Comment by jerrykrinock** [comment]
OK, it works good in my apps now, with all the tests I can think of: New Document, Open, Save, Revert, Versions Browser, Duplicate.

My working code has 3 changes to BSManagedDocument.m…

1.  In `-managedObjectContext`, the message to `-autosaveWithImplicitCancellability::` should be sent to super, not self, to bypass any weird stuff which might have been done by crazy subclassers :)
1.  In `configurePersistentStoreCoordinatorWithDescription::`, I need `performBlock:setUndoManagerBlock` changed to `performBlockAndWait:setUndoManagerBlock`, so that I get my fancy undo manager sooner.
1. In `-saveToURL:ofType:forSaveOperation:completionHandler:`, the kludge based on the BOOL `notLoaded`, which I added some years ago, now prevents the first save when creating a new document in my app, probably because I do not add a new document to the document controller until later, for some reason.  I tested the edge case which this kludge was developed to fix, and it works without this kludge now.  I shall accept the small risk that there might still be an issue in earlier macOS versions.  Therefore, this entire kludge, specifically the BOOL `notLoaded`, all references to it, and my long-winded comment including the call stack, should be removed.

I've attached a patch file with these 3 changes for you to test.

[BSManagedDocument.m.Jerry.patch.txt](https://github.com/jerrykrinock/BSManagedDocument/files/6168819/BSManagedDocument.m.Jerry.patch.txt)

**Comment by evanmiller** [comment]
Quick question: Should the `autosaveWithImplicitCancellability:` message in `fakeSynchronousAutosaveAndReturnError` be sent to `super` as well? I think right now the latter method is only called in the Duplicate workflow, but takes on a larger role in the Share menu pull request.

Otherwise looks good - I guess we can also rip out the Note StackPoint1 and Note StackPoint2 bookmarks in the code, since these were referenced only from the `notLoaded` kludge.

I'll go ahead and commit the patch - just let me know about the first issue above.

**Comment by jerrykrinock** [comment]
Regarding whether the `autosaveWithImplicitCancellability:` message in `-fakeSynchronousAutosaveAndReturnError:` should be sent to super as well: I did some thinking and testing of this.  My answer:  Not 100% sure, but more Yes than No, so, yes do it.

I fond one more thing: "Note JK20170624", starting on line 1500, also appears to be an orphan now, so delete that 22 line comment.

**Comment by evanmiller** [comment]
@jerrykrinock Made the suggested changes. Let me know if you need anything else; I'll keep kicking the tires on my end.

**Pull request merged**
