### PR TITLE
WIP Execute completion handlers on main queue

### PR DESCRIPTION
**Pull request by evanmiller**
Credit to @aufflick. Original patch:

https://github.com/theMikeSwan/BSManagedDocument/commit/150d8f72a4f4e25de1c57d9d15341eb0158da16f

I added one additional instance.

### CODE REVIEW

**Comment by evanmiller** [comment]
This appears to cause a hang in File > Duplicate - probably more work needed.

**Comment by jerrykrinock** [comment]
I am getting the hang even without this pull request, so I have approved this pull request.

**Comment by evanmiller** [comment]
File > Duplicate on an unsaved document produces a hang with this pull request. The hang did not occur before.

I think this can be fixed by replacing `dispatch_async` with `dispatch_sync` for the two instances of fileAccessCompletionHandler.

**Comment by jerrykrinock** [comment]
Wow, I’d like to know what made you “think” that, but we can discuss that later.  BSManagedDocument has always been a learning experience for sure :))

Anyhow, in my apps, and I have not looked into why, this method runs on the main thread, and simply changing it to dispatch_sync causes a crash – **Exception Bad Access > Invalid Operation**.  To fix this, we could test for main thread and still give you the dispatch_sync otherwise.  The following works for me:
```
if ([NSThread isMainThread])
{
    fileAccessCompletionHandler();
    if (completionHandler) completionHandler(error);
}
else
{
    dispatch_sync(dispatch_get_main_queue(), ^{
        fileAccessCompletionHandler();
        if (completionHandler) completionHandler(error);
    });
}
```
What do you think of that, Evan?

**Comment by jerrykrinock** [comment]
I just discovered another issue:

File > Duplicate on an unsaved ("Edited") document produces a new document which does not have any of the unsaved changes from the original document.

This goes back at least several months in my apps, so it is apparently not caused by anything I recently pulled from you or Mike.  Do you see this?  Does it seem to have come from my changes?  Maybe we should test this in the BSManagedDocument test app.  It's easy to imagine how this could occur, given the fundamental that Core Data only reads into memory from its SQLite store as needed.

**Comment by jerrykrinock** [comment]
Hmmm, it works correctly in the last version of Sandvox.

**Comment by evanmiller** [comment]
> Wow, I’d like to know what made you “think” that, but we can discuss that later.

I should have said, when I replaced async with sync, it fixed the hang in my app.

I'd like a better understanding here of what the API is expecting in terms of thread choice and synchronicity. The original patch supposedly fixed an Apple-internal retain count bug, but I never witnessed that bug for myself, and the committer didn't sound all that confident in his solution. So it's possible the solution here involves ripping out dispatching altogether.

https://github.com/theMikeSwan/BSManagedDocument/commit/150d8f72a4f4e25de1c57d9d15341eb0158da16f

**Comment by evanmiller** [comment]
> File > Duplicate on an unsaved ("Edited") document produces a new document which does not have any of the unsaved changes from the original document.

I believe this is the point of forcing an autosave, and then the duplicated file copies the autosaved package. But I'll need to test again on my app.

Why don't you enable "Issues" on this project so that way we can keep track of everything happening on this fork?

**Comment by jerrykrinock** [comment]
Good idea.  Done.  I've moved my comment about the new issue there.

**Comment by jerrykrinock** [comment]
Regarding this [hang reported yesterday](https://github.com/jerrykrinock/BSManagedDocument/pull/2#issuecomment-499569750) by @evanmiller, I've now pushed a new [commit a8f4cc035](https://github.com/jerrykrinock/BSManagedDocument/commit/a8f4cc035f96006089b37e57fe84f3896606d9f9) which, as suggested, changes two dispatch_async to dispatch_sync, and in addition, does not crash when running on main thread.

**Comment by evanmiller** [comment]
With the latest commit, I no longer see a hang or crash. Thanks.

**Pull request merged**
